In [1]:
train_file_path="E:\\Full stack data science-Python pratice\\Machine Learning\\Machine_Learning_Project\\housing\\artifact\\data_ingestion\\2022-10-22_13-08-18\\ingested_data\\train\\housing.csv"

In [2]:
import pandas as pd

In [32]:
data=pd.read_csv(train_file_path)

In [33]:
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  \
0          2237.0       706.0         2.1736             72100.0   
1          2015.0       768.0         6.3373            279600.0   
2           667.0       300.0         2.8750             82700.0   
3           898.0       483.0         2.2264            112500.0   
4          1837.0       580.0         4.4964            238300.0   
...           ...         ...            ...                 ...   
16507      2026.0      1001.0         5.0900            268500.0   
16508      4769.0      1418.0         2.8139             90400.0   
16509       458.0       172.0         3.1797            140400.0   
16510      1208.0       501.0         4.1964            258100.0   
16511       625.0       197.0         3.1319             62700.0   

      ocean_proximity  
0              INLAND  
1          NEAR OCEAN  
2              INLAND  
3          NEAR OCEAN  
4           <1H OCEAN  
...               ...  
16507       <1H OCEAN  
16508          INLAND  
16509       <1H OCEAN  
16510       <1H OCEAN  
16511          INLAND  

[16512 rows x 10 columns]

In [34]:
data.shape

(16512, 10)

In [35]:
## Schema file we need to know the target column
data["median_house_value"]

0         72100.0
1        279600.0
2         82700.0
3        112500.0
4        238300.0
           ...   
16507    268500.0
16508     90400.0
16509    140400.0
16510    258100.0
16511     62700.0
Name: median_house_value, Length: 16512, dtype: float64

In [36]:
data.drop(columns=["median_house_value"])

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income ocean_proximity  
0          2237.0       706.0         2.1736          INLAND  
1          2015.0       768.0         6.3373      NEAR OCEAN  
2           667.0       300.0         2.8750          INLAND  
3           898.0       483.0         2.2264      NEAR OCEAN  
4          1837.0       580.0         4.4964       <1H OCEAN  
...           ...         ...            ...             ...  
16507      2026.0      1001.0         5.0900       <1H OCEAN  
16508      4769.0      1418.0         2.8139          INLAND  
16509       458.0       172.0         3.1797       <1H OCEAN  
16510      1208.0       501.0         4.1964       <1H OCEAN  
16511       625.0       197.0         3.1319          INLAND  

[16512 rows x 9 columns]

In [37]:
x,y=data.drop(columns=["median_house_value"],axis=1),data[["median_house_value"]]

In [38]:
x.shape

(16512, 9)

In [39]:
y.shape

(16512, 1)

In [40]:
x.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [41]:
y.isnull().sum()

median_house_value    0
dtype: int64

In [42]:
## As unique values are not less so we cant work with most_freqent imputation
len(data["total_bedrooms"].unique())

1811

In [43]:
## We can apply imputation to all numerical column..we should specify strategy to replace all null values in all the columns so that
## if in future we get data in which some other columns have Null data then that situation should also get handled.
## We want only categorical columns for imputation

numerical_columns=x.drop(columns=["ocean_proximity"],axis=1)

In [44]:
numerical_columns

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  
0          2237.0       706.0         2.1736  
1          2015.0       768.0         6.3373  
2           667.0       300.0         2.8750  
3           898.0       483.0         2.2264  
4          1837.0       580.0         4.4964  
...           ...         ...            ...  
16507      2026.0      1001.0         5.0900  
16508      4769.0      1418.0         2.8139  
16509       458.0       172.0         3.1797  
16510      1208.0       501.0         4.1964  
16511       625.0       197.0         3.1319  

[16512 rows x 8 columns]

In [45]:
from numpy.lib.function_base import median
from sklearn.impute import SimpleImputer

simpleImputer=SimpleImputer(strategy="median")

In [46]:
simpleImputer.fit_transform(numerical_columns)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [47]:
simpleImputer.fit(numerical_columns)

SimpleImputer(strategy='median')

In [48]:
simpleImputer.transform(numerical_columns)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [49]:
data1=simpleImputer.fit_transform(numerical_columns)

In [50]:
data1

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [51]:
simpleImputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [52]:
x.longitude.median()

-118.51

In [53]:
# Returns median values for all columns
# So whatever null values column is having those values are replaced with these median values
simpleImputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [61]:
## For categorical column replace null values with most frequent category
data["ocean_proximity"].value_counts()

<1H OCEAN     7277
INLAND        5262
NEAR OCEAN    2124
NEAR BAY      1847
ISLAND           2
Name: ocean_proximity, dtype: int64

In [62]:
simple_imputer=SimpleImputer(strategy="most_frequent")

In [65]:
simple_imputer.fit_transform(data[["ocean_proximity"]])

array([['INLAND'],
       ['NEAR OCEAN'],
       ['INLAND'],
       ...,
       ['<1H OCEAN'],
       ['<1H OCEAN'],
       ['INLAND']], dtype=object)

In [105]:
### Custom Transformer Template for Replacing Null values
class FeatureGenerater():
    def __init__(self,strategy="median"):
        self.strategy=strategy

    def fit(self,x):
        self.features_=x.columns
        self.statistics_=[]
        for col in self.features_:
            self.statistics_.append(x[col].median())

    def transoform(self,x):
        for idx,col in enumerate(x.columns):
            x[col].fillna(self.statistics_[idx])

        return x
    def fit_transform(self,x):
        self.fit(x)
        transformed=self.transoform(x)
        return transformed


In [106]:
for idx,index in enumerate(x.columns):
    print(idx,index)

0 longitude
1 latitude
2 housing_median_age
3 total_rooms
4 total_bedrooms
5 population
6 households
7 median_income
8 ocean_proximity


In [107]:
import numpy as np

In [108]:
arr1=np.arange(10)
arr2=np.arange(10,20)
np.c_[arr1,arr2]

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

We can create seperate pipeline for numerical columns and seperate pipeline for categorical columns and in end we have to combine the pieplines 
for that we will need ColumnTransformer

In [109]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [110]:
from sklearn.preprocessing import StandardScaler

In [114]:
## In numerical pipeline we have to specify all the transformation to be done on numerical columns in correct sequence
num_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy="median")),
        ('feature_generator',FeatureGenerater().fit_transform(numerical_columns)),
        ('scaling',StandardScaler(with_mean=False))
    ]
)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [85]:
from sklearn.preprocessing import OneHotEncoder

In [84]:
## Categorical pipeline

cat_pipeline=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy="most_frequent")),
    ('oneHotEncoder',OneHotEncoder())
])

In [87]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [88]:
## Column Transformer for combining num_pipeline and cat_pipeline

preprocessing=ColumnTransformer([
    ('num_pipeline',num_pipeline,['longitude', 'latitude', 'housing_median_age', 'total_rooms','total_bedrooms', 
                                   'population', 'households', 'median_income']),
    ('cat_pipeline',cat_pipeline,['ocean_proximity'])
]
)

NameError: name 'num_pipeline' is not defined

In [94]:
test_file_path="E:\\Full stack data science-Python pratice\\Machine Learning\\Machine_Learning_Project\\housing\\artifact\\data_ingestion\\2022-10-22_13-08-18\\ingested_data\\test\\housing.csv"
test_df=pd.read_csv(test_file_path)

In [ ]:
test_transformed_data=preprocessing(test_df)

In [ ]:
## We got pickle
import dill
with open("preprocessing.pkl","wb") as preprocessed_file:
    dill.dump(preprocessing,preprocessed_file)

In [ ]:
with open("preprocessing.pkl","rb") as preprocessed_file:
    preprocessed_loaded_file=dill.load(preprocessed_file)

In [ ]:
preprocessed_loaded_file.fit_transform(test_df)